name: Build Desktop Apps

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin,x86_64-apple-darwin
          
      - name: Install dependencies
        run: |
          cd apps/desktop
          npm install
          
      - name: Build SDK
        run: |
          cd shared/sdk
          npm install
          npm run build
          
      - name: Build Tauri (M1)
        run: |
          cd apps/desktop
          npm run tauri build -- --target aarch64-apple-darwin
          
      - name: Build Tauri (Intel)
        run: |
          cd apps/desktop
          npm run tauri build -- --target x86_64-apple-darwin
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-builds
          path: |
            apps/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/
            apps/desktop/src-tauri/target/x86_64-apple-darwin/release/bundle/

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: |
          cd apps/desktop
          npm install
          
      - name: Build SDK
        run: |
          cd shared/sdk
          npm install
          npm run build
          
      - name: Build Tauri
        run: |
          cd apps/desktop
          npm run tauri build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-builds
          path: apps/desktop/src-tauri/target/release/bundle/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
          
      - name: Install dependencies
        run: |
          cd apps/desktop
          npm install
          
      - name: Build SDK
        run: |
          cd shared/sdk
          npm install
          npm run build
          
      - name: Build Tauri
        run: |
          cd apps/desktop
          npm run tauri build
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-builds
          path: apps/desktop/src-tauri/target/release/bundle/

